select
o.agreement_number__c,
o.sfid ,
oli.sfid as itemnumber,
oli.OpportunityId,
oli.Part_Number__c,
oli.Renew_Flag__c,
oli.Update_From__c,
oli.Renewal_Status__c,
oli.Quantity,
oli.Actual_Seats__c,
oli.Usage_Type__c,
oli.Deployment__c,
oli.Service_Type__c,
oli.Release__c,
oli.Bundle_Promo_Type__c,
oli.SRP__c,
oli.Total_SRP__c,
oli.ACE_Discount_Eligible__c,
oli.Support_Level__c,
oli.Line_License_Type__c,
oli.Product_Type_Code__c,
oli.PricebookEntryId,
p2.ProductCode,
p2.Is_Bundle__c,
p2.Name,
oli.CQS__c,
oli.Contract_Line_Item__c,
ast.Product_Line_Code__c,
ast.Group_Name__c,
ast.Reseller_Account__c,
ast.Contact__c,
ct.Contact_CSN__c,
ct.Contact_Language__c,
ct.Email,
ct.FirstName,
ct.LastName,
ct.Addr_Line_1__c,
ct.Street_Address_Line_2__c,
ct.Street_Address_Line_3__c,
ct.City__c,
ct.Country__c,
ct.Country_of_Residence__c,
ct.State__c,
ct.Postal_Code__c,
ct.Phone,
ct.Fax,
ct.SFDC_Language_Local_Key__c,
ct.AccountId,
ast.SerialNumber__c,
ast.Asset_Number__c,
ast.ProductDescription__c,
ast.License_Model__c,
ast.Quantity__c,
ast.Status__c,
ast.Renewal_Opportunity__c,
cli.product_sku__c,
act.Account_CSN__c,
ent.service_level__c,
psku.Material_Group__c,
psku.Service_Type__c,
psku.Service_Sales_Type__c,
psku.Name,
psku.usage_type__c,
psku.Program_Type__c,
psku.Subscription_Level__c,
psku.End_User_Type__c,
psku.NFR_Use__c,
psku.Sales_License_Type_Code__c,
psku.Billing_Behavior__c,
psku.Contract_Term__c,
psku.License_Model__c,
psku.Deployment__c,
psku.Product_Line_code__c,
psku.Special_Sales_Program_Type__c,
sc1.Billing_Behavior_Code__c,
sc1.Billing_Behavior__c
from salesforce.opportunity o
JOIN salesforce.opportunitylineitem oli ON oli.opportunityId=o.sfid
JOIN salesforce.PricebookEntry pbe ON pbe.sfid = oli.PricebookEntryId
JOIN salesforce.Product2 p2 ON p2.sfid = pbe.Product2Id
JOIN salesforce.contractlineitem cli ON cli.sfid = oli.Contract_Line_Item__c
JOIN salesforce.Asset__c ast ON ast.sfid = cli.Asset__c
JOIN salesforce.Contact ct ON ct.sfid = ast.Contact__c
JOIN salesforce.Account act ON act.sfid = ct.AccountId
LEFT OUTER JOIN salesforce.Entitlement ent ON ent.sfid = cli.Entitlement__c
JOIN salesforce.Product2 psku ON psku.sfid = cli.product_sku__c
JOIN salesforce.ServiceContract sc1 ON sc1.sfid = cli.ServiceContractId
where o.agreement_number__c = $1