select o.name as opportunity_name,
o.id,
o.sfid,
o.StageName,
o.Deal_Status__c,
o.Permit_Non_ACE_SKU__c,
o.VPA_Contract_Number__c,
o.Non_VPA_Contract_Number__c,
o.Non_PO_Number__c,
o.Non_Dealer_Or_Customer_PO_Number__c,
o.Reference_SRP__c,
o.opportunity_number__c,
o.ADSKOpportunityID__c,
o.RecordTypeId,
rt.Name,
o.Renewal_Status__c,
o.Partner_Contract_Org_CSNs__c,
o.Partner_Incentive__c,
o.CurrencyIsoCode,
o.Asset_End_Date__c,
o.accountId,
a.sfid as enduser_accountId,
a.name as end_user_account_name,
a.Account_csn__c as end_user_acct_csn,
a.Address1__c as end_user_acct_add1,
a.Address2__c as end_user_acct_add2,
a.Address3__c as end_user_acct_add3,
a.City__c as end_user_acct_city,
a.Country__c as end_user_acct_country,
a.State_Province__c as end_user_acct_state,
a.Zip_Postal__c as end_user_acct_zip_code,
a.Language_Code__c as end_user_acct_lang,
o.SoldToAccount__c as sold_to,
o.Partner_Account__c as partner_acct_id,
p.name as reseller_name,
p.Account_CSN__c as reseller_account_csn,
p.Address1__c as reseller_acct_add1,
p.Address2__c as reseller_acct_add2,
p.Address3__c as reseller_acct_add3,
p.City__c as reseller_acct_city,
p.Country__c as reseller_acct_country,
p.State_Province__c as reseller_acct_state,
p.Zip_Postal__c as reseller_acct_zip_code,
p.Language_Code__c as reseller_acct_lang,
rs.name as distributor_name,
rs.Account_csn__c as distributor_csn ,
rs.Address1__c as dist_acct_add1,
rs.Address2__c as dist_acct_add2,
rs.Address3__c as dist_acct_add3,
rs.City__c as dist_acct_city,
rs.Country__c as dist_acct_country,
rs.State_Province__c as dist_acct_state,
rs.Zip_Postal__c as dist_acct_zip_code,
rs.Language_Code__c as dist_acct_lang,
o.service_contract__c as servicecontract_id,
sc.agreement_number__c as agreement_num,
sc.status as status,
sc.startdate as agreement_st_date,
sc.Renew_Online_Flag__c as RenewOnline,
sc.Billing_Behavior__c as billingbehaviour,
sc.Billing_Behavior_Code__c as billingbehaviourcode,
sc.enddate as enddate,
sc.Contract_Term_Code__c as contractTerm,
sc.Contract_Term_UOM__c as UOM,
sc.ContactId as contactId,
ct.Contact_CSN__c as endusercontactCSN,
ct.Contact_Language__c as enduser_cont_lang,
ct.Email as contact_email,
ct.FirstName as contact_fName,
ct.LastName as contact_Lname,
ct.Addr_Line_1__c as contactAddr1,
ct.Shipping_Account_ID__c as contact_shippingId,
ct.Street_Address_Line_2__c as contactAddr2,
ct.Street_Address_Line_3__c as contactAddr3,
ct.City__c as contactCity,
ct.Country__c as contactCountry,
ct.Country_of_Residence__c as contactcountry_residence,
ct.State__c as contactState,
ct.Postal_Code__c as postalCode,
ct.Phone as phone,
ct.Fax as fax,
ct.AccountId as CMacctId,
cta.name as contractMgrname,
cta.Account_csn__C as contractMgrcsn,
cta.Address1__c as contractMgrAddr1,
cta.Address2__c as contractMgrAddr2,
cta.Address3__c as contractMgrAddr3,
cta.City__c as contractMgrCity,
cta.Country__c as cmCountry,
cta.State_Province__c as cmstate,
cta.Zip_Postal__c as cmzipcode,
cta.Language_Code__c as cm_lang,
ct.SFDC_Language_Local_Key__c as sfdc_lang,
o.Renewal_term__c as renewal_term,
o.Contract_Term__c as contract_term,
o.Online_renewal_Flag__c as onlinerenewalflag,
o.Dealer_Or_Customer_PO_Number__c as dealerpo,
o.PO_Number__c as ponumber,
o.End_Date__c as opportunityenddate
from salesforce.opportunity o
LEFT JOIN salesforce.account a ON a.sfid = o.accountId
LEFT JOIN salesforce.recordtype rt ON rt.sfid=o.RecordTypeId
LEFT JOIN salesforce.account p ON p.sfid = o.Partner_Account__c
LEFT JOIN salesforce.servicecontract sc ON sc.sfid = o.service_contract__c
LEFT JOIN salesforce.account rs ON rs.sfid = o.SoldToAccount__c
LEFT JOIN salesforce.contact ct ON ct.sfid = sc.ContactId
LEFT JOIN salesforce.account cta ON cta.sfid = ct.AccountId where o.Opportunity_Type__c='Renewal' and o.opportunity_number__c = $1 