select p.asset_modification__c,
       p.activation_code_required__c,
       p.billing_behavior__c,
       p.is_bundle__c,
       p.contract_term__c,
       p.deployment__c,
       p.description,
       p.end_user_type__c,
       p.fcs_date__c,
       p.fert_certificate__c,
       p.language_code__c,
       p.license_model__c,
       p.license_type__c,
       p.locking_mechanism__c,
       p.material_group__c,
       p.media__c,
       p.alias_name__c,
       p.nfr_use__c,
       p.product_behavior__c,
       p.product_key__c,
       p.product_line_code__c,
       p.program_type__c,
       p.registration_method_code__c,
       p.release_type__c,
       p.sales_license_type__c,
       p.special_sales_program_type__c,
       p.sequence_extension__c,
       p.service_limit_code__c,
       p.service_sales_type__c,
       p.service_type__c,
       p.part_number__c,
       p.status__c,
       p.subscription_level__c,
       p.support_end_date__c,
       p.support_start_date__c,
       p.upgradeable__c,
       p.usage_type__c,
       p.version__c from salesforce.Product2 p
       inner join salesforce.recordtype r on (p.recordtypeid = r.sfid)
       where r.developername = 'Product_SKU' and p.part_number__c in
